Login
shreyansh818bytes/codigo-frontend pull request #3
Opened 2022-10-21 06:49 UTC by manvimandia1603

2022-10-21 19:55 UTC, shreyansh818bytes requested changes

2022-10-21 19:55 UTC, shreyansh818bytes commented on login.js
> +const container = document.querySelector(".container"),
put this file in the js folder

2022-10-21 19:55 UTC, shreyansh818bytes commented on admin.html
> +                        <i class="uil uil-envelope icon"></i>
Where is this icon class defined?

2022-10-21 19:55 UTC, shreyansh818bytes commented on admin.html
> +                        <i class="uil uil-eye-slash showHidePw"></i>
Same as above. Can't find the icon class defined

2022-10-21 19:55 UTC, shreyansh818bytes commented on admin.html
> +                    </div>
We won't be implementing these features for now. Comment out this code for now

2022-10-21 19:55 UTC, shreyansh818bytes commented on admin.html
> +                        <input type="password" class="password" placeholder="Confirm a password" required>
Remove `a` from `Confirm a password`

2022-10-21 19:55 UTC, shreyansh818bytes commented on admin.html
> +                    </div>
same as above, classes not defined anywhere

2022-10-21 19:55 UTC, shreyansh818bytes commented on admin.html
> +                    </div>
No need for this section. Please remove it

2022-10-21 19:55 UTC, shreyansh818bytes commented on login.css
> +
Move this file to css folder, where other css files are kept

2022-10-21 19:55 UTC, shreyansh818bytes commented on login.css
> +}
Please move all major component styles to another stylesheet and keep only page specific styling in this sheet.\
So that all major basic component styling is reusable and design of the website looks consistent.

2022-10-21 19:55 UTC, shreyansh818bytes commented on login.js
> +      pwShowHide = document.querySelectorAll(".showHidePw"),
Why aren't we using jquery?

2022-10-21 19:56 UTC, shreyansh818bytes commented
Where is the file `vectorart.jpg` being used? If nowhere, please remove it

2022-10-23 09:23 UTC, manvimandia1603 commented on login.js
> +      pwShowHide = document.querySelectorAll(".showHidePw"),
> Why aren't we using jquery?

Because i dont know how to use it.

2022-10-30 17:36 UTC, shreyansh818bytes commented on login.js
> +      pwShowHide = document.querySelectorAll(".showHidePw"),
Won't take much time learning. Can start here: https://dzone.com/articles/4-steps-to-learn-jquery-for-beginners

2022-10-30 17:41 UTC, merged